spring:
  main:
    banner-mode: off
  application:
    name: cdc-dedupe
  shell:
    interactive:
      enabled: true
    script:
      enabled: true
logging:
  level:
    root: warn
    run.ecommerce: ${LOG_LEVEL:info}